server:
  port: 9000

spring:
  datasource:
    username: root
    password: 123456
    #url: jdbc:mysql://140.143.194.120:3306/vblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://127.0.0.1:3306/vblog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

qcloud:
  appID: 1257377207
  secretId: AKID1yRp6FZ3CrMxW0GUXghdP0Qky1Uri63p
  secretKey: swUxIeu1zmTzKUYSK6iBTaaP1Zv6b0EG
  bucketName: vblogstore-1257377207
  region: ap-chengdu